import { useEffect, useId, useRef, useState, type KeyboardEvent, type ReactNode } from 'react';
import { Check, ChevronDown } from 'lucide-react';
import { APPS, type AppEntry, type AppId } from './apps.js';

export interface AppSwitcherProps {
  /** The app rendering the switcher. Shown as active in the menu, never as a link. */
  current: AppId;
  /** The app's own brand mark, rendered unchanged. */
  icon: ReactNode;
  label: string;
  /** Collapsed sidebar: icon only, and the menu opens to the right instead of below. */
  collapsed?: boolean;
  apps?: readonly AppEntry[];
}

/** The links in the menu, in order. The current app is not a link, so arrow keys skip it. */
function menuLinks(menu: HTMLElement | null): HTMLAnchorElement[] {
  return menu ? Array.from(menu.querySelectorAll<HTMLAnchorElement>('a[role="menuitem"]')) : [];
}

/**
 * Drop-in replacement for the icon and name at the top of each app's sidebar.
 *
 * Its classes are generated by the app's own Tailwind build, which never scans
 * node_modules on its own — so an app has to import `@gregor_herdmann/web-core/ui.css`,
 * or this renders unstyled. Using the app's `accent-*` palette and `dark:` variant is
 * what makes it match each app without any props for colour.
 */
export function AppSwitcher({ current, icon, label, collapsed = false, apps = APPS }: AppSwitcherProps) {
  const [open, setOpen] = useState(false);
  const rootRef = useRef<HTMLDivElement>(null);
  const triggerRef = useRef<HTMLButtonElement>(null);
  const menuRef = useRef<HTMLDivElement>(null);
  const menuId = useId();

  useEffect(() => {
    if (!open) return;
    menuLinks(menuRef.current)[0]?.focus();
    const onPointerDown = (e: PointerEvent) => {
      if (!rootRef.current?.contains(e.target as Node)) setOpen(false);
    };
    document.addEventListener('pointerdown', onPointerDown);
    return () => document.removeEventListener('pointerdown', onPointerDown);
  }, [open]);

  function onTriggerKeyDown(e: KeyboardEvent) {
    if (!open && (e.key === 'ArrowDown' || e.key === 'ArrowUp')) {
      e.preventDefault();
      setOpen(true);
    }
  }

  function onKeyDown(e: KeyboardEvent) {
    if (!open) return;
    if (e.key === 'Escape') {
      e.preventDefault();
      setOpen(false);
      triggerRef.current?.focus();
      return;
    }
    // Tabbing out leaves the menu behind rather than trapping focus in it.
    if (e.key === 'Tab') {
      setOpen(false);
      return;
    }
    const links = menuLinks(menuRef.current);
    if (links.length === 0) return;
    const i = links.indexOf(document.activeElement as HTMLAnchorElement);
    const next = {
      ArrowDown: links[(i + 1) % links.length],
      ArrowUp: links[(i - 1 + links.length) % links.length],
      Home: links[0],
      End: links[links.length - 1],
    }[e.key];
    if (next) {
      e.preventDefault();
      next.focus();
    }
  }

  return (
    <div ref={rootRef} className="relative min-w-0" onKeyDown={onKeyDown}>
      <button
        ref={triggerRef}
        type="button"
        aria-haspopup="menu"
        aria-expanded={open}
        aria-controls={open ? menuId : undefined}
        aria-label={collapsed ? label : undefined}
        title={collapsed ? label : undefined}
        onClick={() => setOpen((o) => !o)}
        onKeyDown={onTriggerKeyDown}
        className={`group flex min-w-0 cursor-pointer items-center rounded-lg transition-colors hover:bg-slate-50 focus-visible:outline-2 focus-visible:outline-accent-500 dark:hover:bg-slate-800 ${
          collapsed ? 'p-1.5' : '-mx-2 gap-2 px-2 py-1.5'
        }`}
      >
        {icon}
        {!collapsed && (
          <>
            <span className="truncate text-sm font-semibold text-slate-800 dark:text-slate-100">{label}</span>
            <ChevronDown
              size={14}
              aria-hidden="true"
              data-testid="app-switcher-chevron"
              className={`shrink-0 text-slate-400 transition duration-200 dark:text-slate-500 ${
                open ? 'rotate-180 opacity-100' : 'opacity-0 group-hover:opacity-100 group-focus-visible:opacity-100'
              }`}
            />
          </>
        )}
      </button>

      {open && (
        <div
          ref={menuRef}
          id={menuId}
          role="menu"
          aria-label="Switch app"
          className={`absolute z-50 w-72 rounded-xl border border-slate-200 bg-white p-1.5 shadow-lg dark:border-slate-700 dark:bg-slate-900 ${
            collapsed ? 'left-full top-0 ml-2' : 'left-0 top-full mt-2'
          }`}
        >
          {apps.map((app) => {
            const Icon = app.icon;
            const isCurrent = app.id === current;
            const body = (
              <>
                <span
                  className={`shrink-0 rounded-md p-1.5 ${
                    isCurrent
                      ? 'bg-accent-100 text-accent-700 dark:bg-accent-900/40 dark:text-accent-300'
                      : 'bg-slate-100 text-slate-500 dark:bg-slate-800 dark:text-slate-400'
                  }`}
                >
                  <Icon size={16} aria-hidden="true" />
                </span>
                <span className="min-w-0 flex-1">
                  <span className="block text-sm font-medium text-slate-800 dark:text-slate-100">{app.name}</span>
                  <span className="block truncate text-xs text-slate-500 dark:text-slate-400">{app.description}</span>
                </span>
                {isCurrent && (
                  <Check size={14} aria-hidden="true" className="shrink-0 text-accent-600 dark:text-accent-400" />
                )}
              </>
            );
            const row = 'flex items-center gap-3 rounded-lg px-2 py-2 text-left outline-none';

            return isCurrent ? (
              <div
                key={app.id}
                role="menuitem"
                aria-current="page"
                aria-disabled="true"
                className={`${row} bg-accent-50 dark:bg-accent-900/20`}
              >
                {body}
              </div>
            ) : (
              // Same tab: this is a switcher. A plain link still honours cmd- and
              // middle-click for anyone who wants a new tab.
              <a
                key={app.id}
                role="menuitem"
                href={app.url}
                tabIndex={-1}
                onClick={() => setOpen(false)}
                className={`${row} hover:bg-slate-50 focus:bg-slate-50 dark:hover:bg-slate-800 dark:focus:bg-slate-800`}
              >
                {body}
              </a>
            );
          })}
        </div>
      )}
    </div>
  );
}
